# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0002_auto_20180519_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_string',
            field=models.TextField(blank=True),
        ),
    ]
